### PR TITLE
fix package.json error

### PR DESCRIPTION
**Pull request by Hector6704**
Error when installing the module, the main script was wrong

### CODE REVIEW

**Comment by MeguminSama** [comment]
The structures are exported out to dist/index.js  and dist/index.ts

you can import structures with

import {StructureName} from 'discord-slash-commands'

**Comment by MeguminSama** [comment]
Please provide me with the error you were getting so I can diagnose your problem

**Comment by Hector6704** [comment]
Hi, yeah actually my PR didn't fix it. When starting my bot with npm, it's
saying that it cannot find the index.js file (in the slash-commands
module), and that the `main` script of your package.json is wrong

**Comment by MeguminSama** [comment]
did you install via npm or clone the package

**Comment by Hector6704** [comment]
I'm using yarn

**Comment by MeguminSama** [comment]
yarn installs from the npm repository.

can you show me what's inside `node_modules/discord-slash-commands` ?

**Comment by Hector6704** [comment]
Oh wait, does it only work for TS bots? Mine is JS

**Comment by MeguminSama** [comment]
The dist folder contains compiled JS code. it works for JS bots.

**Pull request closed without merging**
